<?php
/**
 * Copyright (c) 2026 BroSolutions
 * All rights reserved
 *
 * This product includes proprietary software developed at BroSolutions, Ukraine
 * For more information see https://www.brosolutions.net/
 *
 * To obtain a valid license for using this software please contact us at
 * contact@brosolutions.net
 */
declare(strict_types=1);

use BroSolutions\DiscontinuedProducts\Block\Product\View\DiscontinuedNotice;
use Magento\Framework\Escaper;

/**
 * @var DiscontinuedNotice $block
 * @var Escaper $escaper
 */
?>
<?php if ($block->isDiscontinued() && $block->getMessage() !== ''): ?>
    <div class="message info discontinued-product-notice">
        <span><?= $escaper->escapeHtml($block->getMessage()) ?></span>
    </div>
<?php endif; ?>
